version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - local-web
  
  db-sql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE : track_books
      MYSQL_ROOT_PASSWORD: brew
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: eps
      MYSQL_PASSWORD: brew
    volumes:
      - type: volume
        source: sql-data
        target: /var/lib/mysql
    networks:
      - local-web

networks:
  local-web:
    driver: bridge

volumes:
  sql-data:
    external: true
    name: sql-data
